# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f7d4ad47615bc1e5c63379015355e22e08fce52d33690c357cd41dd50c8c1571b37a1e9050d36560ae56b07c77f330504d10a5706c7bd6b36f664811badd92a

test:
  secret_key_base: 2d481e5b7a142ddfd3095309f5a270d4b129d1173e9914f5ebcbac676e7f2f7fc8bc702f074d9d6ebfe4b9cf4a9a6d0f61f5a4c9ee8ab55aa3ce9a4a89b253a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
